var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),n,p=!1,ha,q,r,ia,ja,u,v,w,x,ka;
function la(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ma;async function na(a){if(!n)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ma&&n)a=new Uint8Array(n);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),la(d)}}
async function pa(a){var b=ma;if(!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ra=a=>{for(;0<a.length;)a.shift()(h)},sa=[],ta=[],ua=()=>{var a=h.preRun.shift();ta.push(a)},y=0,va=null,wa=!0,xa=[],z=a=>{var b=xa[a];b||(xa[a]=b=ya.get(a));return b},za=globalThis.TextDecoder&&new TextDecoder,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&za)return za.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<
6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Aa=0,Ba={},Ca=a=>{if(!(a instanceof qa||"unwind"==a))throw a;},Da=a=>{ha=a;wa||0<Aa||(h.onExit?.(a),p=!0);throw new qa(a);},Ea=()=>{if(!(wa||0<Aa))try{var a=ha;ha=a;Da(a)}catch(b){Ca(b)}},Fa=a=>{if(!p)try{a(),Ea()}catch(b){Ca(b)}};
function Ga(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Ha=(a,b)=>setTimeout(()=>{Fa(a)},b),Ia=!1,Ja=[];
function Ka(){function a(){Ia=document.pointerLockElement===h.canvas}if(!La){La=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ia&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ma(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Ee:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Na&&(e=Oa(a,f)))var l=B[e].$d}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Pa(e),Ja.forEach(m=>m()),Ka());return l}
var La,C=12288,Qa=!1,Ra=0,Sa=0,Ta=0,D={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ua={},Va,E,Wa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Xa=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ya=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Za=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},$a=1,ab=[],G=[],bb=[],H=[],J=[],K=[],cb=[],B=[],M=[],db={},eb=4,fb=0,gb=a=>{for(var b=$a++,c=a.length;c<b;c++)a[c]=null;return b},hb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=E[c](),g=f&&gb(d);f?(f.name=g,d[g]=f):N||=1282;u[b+4*e>>2]=g}},Oa=(a,b)=>{a.ze||(a.ze=a.getContext,a.getContext=function(d,e){e=a.ze(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ib(c,b):0},ib=(a,b)=>{var c=
gb(B),d={handle:c,attributes:b,version:b.Ee,$d:a};a.canvas&&(a.canvas.ce=d);B[c]=d;if("undefined"==typeof b.Qe||b.Qe)if((a=d)||(a=jb),!a.Ve){a.Ve=!0;a=a.$d;a.lf=a.getExtension("WEBGL_multi_draw");a.Se=a.getExtension("EXT_polygon_offset_clamp");a.Re=a.getExtension("EXT_clip_control");a.Ze=a.getExtension("WEBGL_polygon_mode");Wa(a);Xa(a);Ya(a);a.Zd=a.getExtension("EXT_disjoint_timer_query");for(var e of Za(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},Pa=a=>{jb=B[a];
h.ctx=E=jb?.$d},Na={},N,jb,kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},O=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&
63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Q=a=>{var b=kb(a)+1,c=P(b);c&&O(a,c,b);return c},Ab=(a,b,c,d,e)=>{function f(){return g<lb?(Ea(),!1):!0}mb=a;nb=d;var g=lb;ob=!1;pb=function(){if(!p)if(0<qb.length){var l=qb.shift();l.gf(l.$e);if(rb){var m=rb,t=0==m%1?m-1:Math.floor(m);rb=l.cf?t:(8*m+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=rb??0,t=sb.ff??0,m?m<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(pb,
0)}else if(f())if(tb=tb+1|0,1==ub&&1<vb&&0!=tb%vb)R();else{0==ub&&(wb=performance.now());a:if(!p){for(l of xb)if(!1===l())break a;Fa(a);for(m of yb)m()}f()&&R()}};e||(0<b?zb(0,1E3/b):zb(1,1),R());if(c)throw"unwind";},ob=!1,R=null,lb=0,mb=null,nb=0,ub=0,vb=0,tb=0,qb=[],xb=[],yb=[];function Bb(){R=null;lb++}var Cb=0;function Db(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Cb)Cb=b+1E3/60;else for(;b+2>=Cb;)Cb+=1E3/60;setTimeout(a,Math.max(Cb-b,0))}}
var sb={},pb,rb,wb,Eb,zb=(a,b)=>{ub=a;vb=b;if(mb)if(ob||=!0,0==a)R=function(){setTimeout(pb,Math.max(0,wb+b-performance.now())|0)};else if(1==a)R=function(){Db(pb)};else if(2==a){if(!Eb)if(globalThis.setImmediate)Eb=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Eb=d=>{c.push(d);postMessage("setimmediate","*")}}R=function(){Eb(pb)}}},Fb=[],Gb=(a,b)=>{Fb.length=0;for(var c;c=r[a++];){var d=105!=
c;d&=112!=c;b+=d&&b%8?4:0;Fb.push(112==c?v[b>>2]:106==c?ka[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Fb},Hb=clearTimeout;function Ib(a){var b=S.Ud[a];b.target.removeEventListener(b.Sd,b.Ce,b.Wd);S.Ud.splice(a,1)}function Jb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of S.ae)if(e.te==a&&d(e.Ae,c))return;S.ae.push({te:a,Ge:b,Ae:c});S.ae.sort((f,g)=>f.Ge<g.Ge)}function Kb(a){S.ae=S.ae.filter(b=>b.te!=a)}
function Lb(){return navigator.userActivation?navigator.userActivation.isActive:S.pe&&S.Ke.ee}function Mb(){if(Lb()){var a=S.ae;S.ae=[];for(var b of a)b.te(...b.Ae)}}function T(a){if(!a.target)return-4;if(a.Td)a.Ce=function(c){++S.pe;S.Ke=a;Mb();a.Yd(c);Mb();--S.pe},a.target.addEventListener(a.Sd,a.Ce,a.Wd),S.Ud.push(a);else for(var b=0;b<S.Ud.length;++b)S.Ud[b].target==a.target&&S.Ud[b].Sd==a.Sd&&Ib(b--);return 0}
function Nb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={af:0,oe:0,qe:0,ke:0,ye:0,ve:0,me:0,ef:0,mf:0,df:0,ne:0,re:0,xe:0,ue:0,nf(){for(;S.Ud.length;)Ib(S.Ud.length-1);S.ae=[]},pe:0,ae:[],Ud:[],Xe:(a,b)=>{for(var c=0;c<S.Ud.length;++c)S.Ud[c].target!=a||b&&b!=S.Ud[c].Sd||Ib(c--)},pf(a){let b=!1;for(let c=0;c<S.Ud.length;++c){const d=S.Ud[c];d.target===a.target&&d.Vd===a.Vd&&d.Td===a.Td&&d.Xd===a.Xd&&(Ib(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ob=[0,document,window],U=a=>
{a=2<a?a?A(r,a):"":a;return Ob[a]||document.querySelector(a)},Qb=a=>{var b=kb(a)+1,c=Pb(b);O(a,c,b);return c},Rb=a=>{var b=V(),c=Pb(8),d=c+4;a=Qb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];W(b);return c},Sb=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Tb=(a,b,c)=>{if(a.bf){var d=V();a=Qb(a.id);Sb(a,b,c);W(d)}else a.width=b,a.height=c},Ub={},Vb=a=>{function b(){Ga()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Tb(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=t,a.style.paddingRight=F,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=Cc,a.style.marginRight=Dc,a.style.marginTop=Ec,a.style.marginBottom=Fc,document.body.style.margin=Gc,document.documentElement.style.overflow=Hc,document.body.scroll=Ic,a.style.be=Jc,a.ce&&a.ce.$d.viewport(0,0,d,e),Ub.fe&&z(Ub.fe)(37,
0,Ub.Be))}var c=Rb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,t=a.style.paddingLeft,F=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,Cc=a.style.marginLeft,Dc=a.style.marginRight,Ec=a.style.marginTop,Fc=a.style.marginBottom,Gc=document.body.style.margin,Hc=document.documentElement.style.overflow,Ic=document.body.scroll,Jc=a.style.be;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Wb=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Xb=a=>0>Ob.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Yb=(a,b)=>{if(0!=b.se||0!=b.le){Vb(a);var c=b.Ye?innerWidth:screen.width,d=b.Ye?innerHeight:screen.height,e=Xb(a),f=e.width;e=e.height;var g=Rb(a),l=g[0];g=g[1];3==b.se?(Wb(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.se&&(c*g<l*d?(f=g*c/l,Wb(a,(d-f)/2,0),d=f):(f=l*d/g,Wb(a,0,(c-f)/2),c=f));var m;(m=a.style).backgroundColor||(m.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Te&&(a.style.be="optimizeSpeed",a.style.be="-moz-crisp-edges",a.style.be="-o-crisp-edges",a.style.be="-webkit-optimize-contrast",a.style.be="optimize-contrast",a.style.be="crisp-edges",a.style.be="pixelated");m=2==b.le?devicePixelRatio:1;0!=b.le&&(c=c*m|0,d=d*m|0,Tb(a,c,d),a.ce&&a.ce.$d.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Ub=b;b.fe&&z(b.fe)(37,0,b.Be);return 0},Zb=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},$b=[],ac=(a,b,c,d,e,f,g,l)=>{b=G[b];if(a=E[a](b,c))d=l&&O(a.name,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},bc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(N||=1280);return;case 36345:d=0;break;case 34466:var e=E.getParameter(34467);d=e?e.length:0}if(void 0===
d)switch(e=E.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=
e.name|0}catch(f){N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else N||=1281},cc=(a,b,c)=>{if(c){a=E.Zd.getQueryObjectEXT(M[a],b);var d;"boolean"==
typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else N||=1281},dc=(a,b,c)=>{if(c){a=E.Zd.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else N||=1281},ec=()=>{var a=Za(E);return a=a.concat(a.map(b=>"GL_"+b))},fc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),gc=a=>{var b=a.de,c=a.Ie,d;if(!b){a.de=b={};a.He={};var e=E.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=E.getActiveUniform(a,d);var g=f.name;f=f.size;var l=fc(g);l=0<l?g.slice(0,l):g;var m=a.we;a.we+=
f;c[l]=[f,m];for(g=0;g<f;++g)b[m]=g,a.He[m++]=l}}},X=a=>{var b=E.Le;if(b){var c=b.de[a];"number"==typeof c&&(b.de[a]=c=E.getUniformLocation(b,b.He[a]+(0<c?`[${c}]`:"")));return c}N||=1282},hc=(a,b,c,d)=>{if(c)if(a=G[a],gc(a),a=E.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else N||=1281},ic=(a,b,c,d)=>{if(c)if(a=E.getVertexAttrib(a,b),34975==b)u[c>>
2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else N||=1281},jc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ja;b=d*((fb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+eb-1&-eb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Y=[],kc=[],lc=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Lb()?Yb(a,b):b.Pe?(Jb(Yb,1,[a,b]),1):-2:-3:-4},mc=(a,b)=>{var c={target:U(2),Sd:"beforeunload",Vd:28,Xd:a,Td:b,Yd:d=>{var e=z(b)(28,0,a);e&&=e?A(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},Wd:!0};return T(c)},nc=(a,b,c,d,e,f)=>{S.me||(S.me=P(256));a={target:U(a),Sd:f,Vd:e,Xd:b,Td:d,Yd:g=>{var l=g.target.id?g.target.id:"",m=S.me;
O(Nb(g.target),m+0,128);O(l,m+128,128);z(d)(e,m,b)&&g.preventDefault()},Wd:c};return T(a)},oc=(a,b,c,d,e)=>{S.ne||(S.ne=P(276));return T({target:a,Sd:e,Vd:19,Xd:b,Td:d,Yd:f=>{var g=S.ne,l=Ga(),m=!!l;q[g]=m;q[g+1]=S.fullscreenEnabled();var t=m?l:S.We,F=t?.id||"";O(Nb(t),g+2,128);O(F,g+130,128);u[g+260>>2]=t?t.clientWidth:0;u[g+264>>2]=t?t.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;m&&(S.We=l);z(d)(19,g,b)&&f.preventDefault()},Wd:c})},pc=(a,b,c,d,e)=>{S.oe||(S.oe=P(1240));b={target:U(2),
ee:!0,Sd:e,Vd:d,Xd:a,Td:c,Yd:f=>{var g=S.oe,l=f.gamepad;x[g>>3]=l.timestamp;for(var m=0;m<l.axes.length;++m)x[g+8*m+16>>3]=l.axes[m];for(m=0;m<l.buttons.length;++m)x[g+8*m+528>>3]="object"==typeof l.buttons[m]?l.buttons[m].value:l.buttons[m];for(m=0;m<l.buttons.length;++m)q[g+m+1040]="object"==typeof l.buttons[m]?l.buttons[m].pressed:1==l.buttons[m];q[g+1104]=l.connected;u[g+1108>>2]=l.index;u[g+8>>2]=l.axes.length;u[g+12>>2]=l.buttons.length;O(l.id,g+1112,64);O(l.mapping,g+1176,64);z(c)(d,g,a)&&
f.preventDefault()},Wd:b};return T(b)},qc=()=>{try{if(navigator.getGamepads)return(S.hf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},rc=(a,b,c,d,e,f)=>{S.qe||(S.qe=P(160));a={target:U(a),Sd:f,Vd:e,Xd:b,Td:d,Yd:g=>{var l=S.qe;x[l>>3]=g.timeStamp;var m=l>>2;u[m+2]=g.location;q[l+12]=g.ctrlKey;q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;q[l+16]=g.repeat;u[m+5]=g.charCode;u[m+6]=g.keyCode;u[m+7]=g.which;O(g.key||"",l+32,32);O(g.code||"",l+64,32);O(g.char||"",l+
96,32);O(g.locale||"",l+128,32);z(d)(e,l,b)&&g.preventDefault()},Wd:c};return T(a)},sc=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ia[2*d+14]=b.button;ia[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=Xb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},tc=(a,b,c,d,e,f)=>{S.ke||(S.ke=P(64));a=U(a);return T({target:a,ee:"mousemove"!=f&&"mouseenter"!=
f&&"mouseleave"!=f,Sd:f,Vd:e,Xd:b,Td:d,Yd:g=>{sc(S.ke,g,a);z(d)(e,S.ke,b)&&g.preventDefault()},Wd:c})},uc=(a,b,c,d)=>{S.re||(S.re=P(257));return T({target:a,Sd:"pointerlockchange",Vd:20,Xd:b,Td:d,Yd:e=>{var f=S.re,g=document.pointerLockElement;q[f]=!!g;var l=g?.id||"";O(Nb(g),f+1,128);O(l,f+129,128);z(d)(20,f,b)&&e.preventDefault()},Wd:c})},vc=(a,b,c,d)=>{S.ve||(S.ve=P(36));a=U(a);return T({target:a,Sd:"resize",Vd:10,Xd:b,Td:d,Yd:e=>{if(e.target==a){var f=document.body;if(f){var g=S.ve;u[g>>2]=0;
u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;z(d)(10,g,b)&&e.preventDefault()}}},Wd:c})},wc=(a,b,c,d,e,f)=>{S.ue||(S.ue=P(1552));a=U(a);return T({target:a,ee:"touchstart"==f||"touchend"==f,Sd:f,Vd:e,Xd:b,Td:d,Yd:g=>{var l={},m=g.touches;for(var t of m)t.De=t.Fe=0,l[t.identifier]=t;for(var F of g.changedTouches)F.De=1,l[F.identifier]=F;for(var L of g.targetTouches)l[L.identifier].Fe=
1;m=S.ue;x[m>>3]=g.timeStamp;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;t=m+16;F=Xb(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.De,q[t+29]=I.Fe,u[l+8]=I.clientX-(F.left|0),u[l+9]=I.clientY-(F.top|0),t+=48,31<++L)break;u[m+8>>2]=L;z(d)(e,m,b)&&g.preventDefault()},Wd:c})},xc=(a,b,c)=>{var d=Ob[1];S.xe||(S.xe=P(8));return T({target:d,Sd:"visibilitychange",
Vd:21,Xd:a,Td:c,Yd:e=>{var f=S.xe,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;z(c)(21,f,a)&&e.preventDefault()},Wd:b})},yc=(a,b,c,d)=>{S.ye||(S.ye=P(96));return T({target:a,ee:!0,Sd:"wheel",Vd:9,Xd:b,Td:d,Yd:e=>{var f=S.ye;sc(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;z(d)(9,f,b)&&e.preventDefault()},Wd:c})},zc={},Bc=()=>{if(!Ac){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in zc)void 0===zc[b]?delete a[b]:a[b]=zc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ac=c}return Ac},Ac,Kc=[null,[],[]],Lc=()=>a=>crypto.getRandomValues(a),Mc=a=>{(Mc=Lc())(a)};h.requestAnimationFrame=Db;h.pauseMainLoop=Bb;h.resumeMainLoop=function(){lb++;var a=ub,b=vb,c=mb;mb=null;Ab(c,0,!1,nb,!0);zb(a,b);R()};h.preMainLoop&&xb.push(h.preMainLoop);h.postMainLoop&&yb.push(h.postMainLoop);
for(let a=0;32>a;++a)$b.push(Array(a));for(var Nc=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Nc.subarray(0,Z);var Oc=new Int32Array(288);for(Z=0;288>=Z;++Z)kc[Z]=Oc.subarray(0,Z);h.noExitRuntime&&(wa=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(n=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.createContext=Ma;
var Pc={299214:a=>{a=(a?A(r,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return 1===a.length?a.charCodeAt(0):-1},299429:()=>window.innerWidth,299459:()=>window.innerHeight,299490:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Je!==h.canvas&&(d.ge=Ma(h.canvas,!1,!0),d.Je=h.canvas);if(d.w!==a||d.h!==b||d.Ue!==d.ge)d.image=d.ge.createImageData(a,b),d.w=a,d.h=b,d.Ue=d.ge;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof
CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ne!==a&&(d.Me=new Int32Array(a.buffer),d.Oe=new Uint8Array(a.buffer),d.Ne=a),a=d.Me,c=a.length,a.set(u.subarray(b,b+c)),a=d.Oe,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ge.putImageData(d.image,0,0)},300956:(a,b,c,d,e)=>{var f=
document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(u.subarray(e,e+m));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);O(c,
d,c.length+1);return d},301944:a=>{h.canvas&&(h.canvas.style.cursor=a?A(r,a):"")},302027:()=>{h.canvas&&(h.canvas.style.cursor="none")}},Qc,P,Rc,Sc,W,Pb,V,Tc,ya,Xc={Na:(a,b)=>z(a)(b),i:function(){return 0},cb:()=>{},eb:function(){return 0},$a:()=>{},_a:()=>{},H:function(){},ab:()=>{},Qa:()=>la(""),Pa:()=>{wa=!1;Aa=0},Ma:()=>{throw Infinity;},Ua:function(){return-52},Va:function(){},Ra:(a,b)=>{Ba[a]&&(clearTimeout(Ba[a].id),delete Ba[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ba[a];Fa(()=>Rc(a,
performance.now()))},b);Ba[a]={id:c,qf:b};return 0},Ta:a=>{if(12448==a)return C=12288,1;C=12300;return 0},ad:(a,b,c,d,e)=>{if(62E3!=a)C=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)D.alpha=0<u[b+4>>2];else if(12325==a)D.depth=0<u[b+4>>2];else if(12326==a)D.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],D.antialias=0<a;else if(12338==a)a=u[b+4>>2],D.antialias=1==a;else if(12544==a)D.jf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),C=12288,c=1):
(C=12300,c=0)}return c},Gc:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return C=12292,0;d+=8}if(2!=a)return C=12293,0;D.Ee=a-1;D.kf=0;Va=Oa(h.canvas,D);if(0!=Va)return C=12288,Pa(Va),Ja.forEach(e=>e()),Pa(null),62004;C=12297;return 0},kc:(a,b)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;C=12288;return 62006},vc:(a,b)=>{if(62E3!=a)return C=12296,0;if(62004!=b)return C=12294,0;a=Va;jb===B[a]&&(jb=null);"object"==typeof S&&
S.Xe(B[a].$d.canvas);B[a]?.$d.canvas&&(B[a].$d.canvas.ce=void 0);B[a]=null;C=12288;Ra==b&&(Ra=0);return 1},$b:(a,b)=>{if(62E3!=a)return C=12296,0;if(62006!=b)return C=12301,1;Sa==b&&(Sa=0);Ta==b&&(Ta=0);C=12288;return 1},Rc:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;if(!d)return C=12300,0;C=12288;switch(c){case 12320:return u[d>>2]=D.alpha?32:24,1;case 12321:return u[d>>2]=D.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=
8,1;case 12325:return u[d>>2]=D.depth?24:0,1;case 12326:return u[d>>2]=D.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=D.antialias?4:0,1;case 12338:return u[d>>2]=D.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>
2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return C=12292,0}},I:a=>{C=12288;return 0!=a&&1!=a?0:62E3},Ha:()=>C,wd:(a,b,c)=>{if(62E3!=a)return C=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Qa=!0;C=12288;return 1},Qb:(a,b,c,d)=>{if(62E3!=a)return C=
12296,0;if(0!=d&&62004!=d)return C=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return C=12301,0;Pa(d?Va:null);Ra=d;Ta=b;Sa=c;C=12288;return 1},Ia:(a,b)=>{if(62E3!=a)return C=12296,0;C=12288;if(Ua[b])return Ua[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return C=12300,0}return Ua[b]=a},Eb:()=>{if(Qa)if(E)if(E.isContextLost())C=12302;else return C=12288,1;else C=12290;else C=12289;return 0},
tb:(a,b)=>{if(62E3!=a)return C=12296,0;0==b?zb(0,0):zb(1,b);C=12288;return 1},ld:a=>{if(62E3!=a)return C=12296,0;Ta=Sa=Ra=0;Qa=!1;C=12288;return 1},bb:()=>{C=12288;return 1},ib:()=>{C=12288;return 1},b:(a,b,c)=>{b=Gb(b,c);return Pc[a](...b)},Fa:(a,b,c)=>{b=Gb(b,c);return Pc[a](...b)},J:()=>{Bb();mb=null},U:Hb,fb:()=>Date.now(),za:()=>{if(!S.fullscreenEnabled())return-1;Kb(Yb);var a=Ob[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&
a.webkitExitFullscreen();else return-1;return 0},Ea:()=>{Kb(Zb);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},Fb:a=>{wa=!1;Aa=0;ha=a;Da(a)},d:()=>devicePixelRatio,a:(a,b,c)=>{a=U(a);if(!a)return-4;a=Xb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},h:()=>performance.now(),Ga:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},fa:a=>E.activeTexture(a),ea:(a,b)=>{E.attachShader(G[a],K[b])},va:(a,b)=>{E.Zd.beginQueryEXT(a,M[b])},da:(a,b,c)=>{E.bindAttribLocation(G[a],b,c?
A(r,c):"")},ca:(a,b)=>{E.bindBuffer(a,ab[b])},ba:(a,b)=>{E.bindFramebuffer(a,bb[b])},aa:(a,b)=>{E.bindRenderbuffer(a,H[b])},$:(a,b)=>{E.bindTexture(a,J[b])},na:a=>{E.bindVertexArray(cb[a])},_:(a,b,c,d)=>E.blendColor(a,b,c,d),Z:a=>E.blendEquation(a),Y:(a,b)=>E.blendEquationSeparate(a,b),X:(a,b)=>E.blendFunc(a,b),W:(a,b,c,d)=>E.blendFuncSeparate(a,b,c,d),V:(a,b,c,d)=>{E.bufferData(a,c?r.subarray(c,c+b):b,d)},T:(a,b,c,d)=>{E.bufferSubData(a,b,r.subarray(d,d+c))},S:a=>E.checkFramebufferStatus(a),R:a=>
E.clear(a),Q:(a,b,c,d)=>E.clearColor(a,b,c,d),P:a=>E.clearDepth(a),O:a=>E.clearStencil(a),hb:(a,b)=>{E.Re.clipControlEXT(a,b)},N:(a,b,c,d)=>{E.colorMask(!!a,!!b,!!c,!!d)},M:a=>{E.compileShader(K[a])},L:(a,b,c,d,e,f,g,l)=>{E.compressedTexImage2D(a,b,c,d,e,f,r.subarray(l,l+g))},K:(a,b,c,d,e,f,g,l,m)=>{E.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(m,m+l))},Gd:(a,b,c,d,e,f,g,l)=>E.copyTexImage2D(a,b,c,d,e,f,g,l),Fd:(a,b,c,d,e,f,g,l)=>E.copyTexSubImage2D(a,b,c,d,e,f,g,l),Ed:()=>{var a=gb(G),b=E.createProgram();
b.name=a;b.je=b.he=b.ie=0;b.we=1;G[a]=b;return a},Dd:a=>{var b=gb(K);K[b]=E.createShader(a);return b},Cd:a=>E.cullFace(a),Bd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ab[d];e&&(E.deleteBuffer(e),e.name=0,ab[d]=null)}},Ad:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=bb[d];e&&(E.deleteFramebuffer(e),e.name=0,bb[d]=null)}},zd:a=>{if(a){var b=G[a];b?(E.deleteProgram(b),b.name=0,G[a]=null):N||=1281}},xa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(E.Zd.deleteQueryEXT(e),M[d]=null)}},
yd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(E.deleteRenderbuffer(e),e.name=0,H[d]=null)}},xd:a=>{if(a){var b=K[a];b?(E.deleteShader(b),K[a]=null):N||=1281}},vd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(E.deleteTexture(e),e.name=0,J[d]=null)}},ma:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];E.deleteVertexArray(cb[d]);cb[d]=null}},ud:a=>E.depthFunc(a),td:a=>{E.depthMask(!!a)},sd:(a,b)=>E.depthRange(a,b),rd:(a,b)=>{E.detachShader(G[a],K[b])},qd:a=>E.disable(a),pd:a=>
{E.disableVertexAttribArray(a)},od:(a,b,c)=>{E.drawArrays(a,b,c)},ia:(a,b,c,d)=>{E.drawArraysInstanced(a,b,c,d)},ja:(a,b)=>{for(var c=$b[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];E.drawBuffers(c)},nd:(a,b,c,d)=>{E.drawElements(a,b,c,d)},ha:(a,b,c,d,e)=>{E.drawElementsInstanced(a,b,c,d,e)},md:a=>E.enable(a),kd:a=>{E.enableVertexAttribArray(a)},ua:a=>{E.Zd.endQueryEXT(a)},jd:()=>E.finish(),id:()=>E.flush(),hd:(a,b,c,d)=>{E.framebufferRenderbuffer(a,b,c,H[d])},gd:(a,b,c,d,e)=>{E.framebufferTexture2D(a,b,c,J[d],
e)},fd:a=>E.frontFace(a),ed:(a,b)=>{hb(a,b,"createBuffer",ab)},cd:(a,b)=>{hb(a,b,"createFramebuffer",bb)},ya:(a,b)=>{for(var c=0;c<a;c++){var d=E.Zd.createQueryEXT();if(!d){for(N||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=gb(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},bd:(a,b)=>{hb(a,b,"createRenderbuffer",H)},$c:(a,b)=>{hb(a,b,"createTexture",J)},la:(a,b)=>{hb(a,b,"createVertexArray",cb)},dd:a=>E.generateMipmap(a),_c:(a,b,c,d,e,f,g)=>ac("getActiveAttrib",a,b,c,d,e,f,g),Zc:(a,b,c,d,e,f,g)=>ac("getActiveUniform",
a,b,c,d,e,f,g),Yc:(a,b,c,d)=>{a=E.getAttachedShaders(G[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},Xc:(a,b)=>E.getAttribLocation(G[a],b?A(r,b):""),Wc:(a,b)=>bc(a,b,4),Vc:(a,b,c)=>{c?u[c>>2]=E.getBufferParameter(a,b):N||=1281},Uc:()=>{var a=E.getError()||N;N=0;return a},Tc:(a,b)=>bc(a,b,2),Sc:(a,b,c,d)=>{a=E.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Qc:(a,b)=>bc(a,b,0),Oc:(a,b,
c,d)=>{a=E.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},Pc:(a,b,c)=>{if(c)if(a>=$a)N||=1281;else if(a=G[a],35716==b)a=E.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.je){var d=E.getProgramParameter(a,35718);for(b=0;b<d;++b)a.je=Math.max(a.je,E.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.je}else if(35722==b){if(!a.he)for(d=E.getProgramParameter(a,35721),b=0;b<d;++b)a.he=Math.max(a.he,E.getActiveAttrib(a,
b).name.length+1);u[c>>2]=a.he}else if(35381==b){if(!a.ie)for(d=E.getProgramParameter(a,35382),b=0;b<d;++b)a.ie=Math.max(a.ie,E.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ie}else u[c>>2]=E.getProgramParameter(a,b);else N||=1281},pa:cc,ra:dc,oa:cc,qa:dc,sa:(a,b,c)=>{c?u[c>>2]=E.Zd.getQueryEXT(a,b):N||=1281},Nc:(a,b,c)=>{c?u[c>>2]=E.getRenderbufferParameter(a,b):N||=1281},Lc:(a,b,c,d)=>{a=E.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},Kc:(a,b,c,
d)=>{a=E.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},Jc:(a,b,c,d)=>{if(a=E.getShaderSource(K[a]))b=0<b&&d?O(a,d,b):0,c&&(u[c>>2]=b)},Mc:(a,b,c)=>{c?35716==b?(a=E.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=E.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=E.getShaderParameter(K[a],b):N||=1281},Ic:a=>{var b=db[a];if(!b){switch(a){case 7939:b=Q(ec().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
E.getParameter(a))||(N||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${E.getParameter(7938)})`);break;case 35724:b=E.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:N||=1280}db[a]=b}return b},Hc:(a,b,c)=>{c?w[c>>2]=E.getTexParameter(a,b):N||=1281},Fc:(a,b,c)=>{c?u[c>>2]=E.getTexParameter(a,b):N||=1281},Cc:(a,b)=>{b=b?A(r,b):"";if(a=G[a]){gc(a);var c=a.de,d=0,
e=b,f=fc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ie[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||E.getUniformLocation(a,b)))return d}else N||=1281;return-1},Ec:(a,b,c)=>{hc(a,b,c,2)},Dc:(a,b,c)=>{hc(a,b,c,0)},zc:(a,b,c)=>{c?u[c>>2]=E.getVertexAttribOffset(a,b):N||=1281},Bc:(a,b,c)=>{ic(a,b,c,2)},Ac:(a,b,c)=>{ic(a,b,c,5)},yc:(a,b)=>E.hint(a,b),xc:a=>(a=ab[a])?E.isBuffer(a):0,wc:a=>E.isEnabled(a),uc:a=>(a=bb[a])?E.isFramebuffer(a):0,tc:a=>(a=G[a])?E.isProgram(a):0,wa:a=>(a=M[a])?E.Zd.isQueryEXT(a):
0,sc:a=>(a=H[a])?E.isRenderbuffer(a):0,rc:a=>(a=K[a])?E.isShader(a):0,qc:a=>(a=J[a])?E.isTexture(a):0,ka:a=>(a=cb[a])?E.isVertexArray(a):0,pc:a=>E.lineWidth(a),oc:a=>{a=G[a];E.linkProgram(a);a.de=0;a.Ie={}},nc:(a,b)=>{3317==a?eb=b:3314==a&&(fb=b);E.pixelStorei(a,b)},gb:(a,b)=>{E.Ze.polygonModeWEBGL(a,b)},mc:(a,b)=>E.polygonOffset(a,b),jb:(a,b,c)=>{E.Se.polygonOffsetClampEXT(a,b,c)},ta:(a,b)=>{E.Zd.queryCounterEXT(M[a],b)},lc:(a,b,c,d,e,f,g)=>{(g=jc(f,e,c,d,g))?E.readPixels(a,b,c,d,e,f,g):N||=1280},
jc:()=>{},ic:(a,b,c,d)=>E.renderbufferStorage(a,b,c,d),hc:(a,b)=>{E.sampleCoverage(a,!!b)},gc:(a,b,c,d)=>E.scissor(a,b,c,d),fc:()=>{N||=1280},ec:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?A(r,g,d?v[d+4*f>>2]:void 0):"";e+=g}E.shaderSource(K[a],e)},dc:(a,b,c)=>E.stencilFunc(a,b,c),cc:(a,b,c,d)=>E.stencilFuncSeparate(a,b,c,d),bc:a=>E.stencilMask(a),ac:(a,b)=>E.stencilMaskSeparate(a,b),_b:(a,b,c)=>E.stencilOp(a,b,c),Zb:(a,b,c,d)=>E.stencilOpSeparate(a,b,c,d),Yb:(a,b,c,d,e,f,g,l,m)=>
{m=m?jc(l,g,d,e,m):null;E.texImage2D(a,b,c,d,e,f,g,l,m)},Xb:(a,b,c)=>E.texParameterf(a,b,c),Wb:(a,b,c)=>{E.texParameterf(a,b,w[c>>2])},Vb:(a,b,c)=>E.texParameteri(a,b,c),Ub:(a,b,c)=>{E.texParameteri(a,b,u[c>>2])},Tb:(a,b,c,d,e,f,g,l,m)=>{m=m?jc(l,g,e,f,m):null;E.texSubImage2D(a,b,c,d,e,f,g,l,m)},Sb:(a,b)=>{E.uniform1f(X(a),b)},Rb:(a,b,c)=>{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);E.uniform1fv(X(a),d)},Pb:(a,b)=>{E.uniform1i(X(a),b)},Ob:(a,b,c)=>{if(288>=
b)for(var d=kc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);E.uniform1iv(X(a),d)},Nb:(a,b,c)=>{E.uniform2f(X(a),b,c)},Mb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);E.uniform2fv(X(a),d)},Lb:(a,b,c)=>{E.uniform2i(X(a),b,c)},Kb:(a,b,c)=>{if(144>=b){b*=2;for(var d=kc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);E.uniform2iv(X(a),d)},Jb:(a,b,c,d)=>{E.uniform3f(X(a),
b,c,d)},Ib:(a,b,c)=>{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);E.uniform3fv(X(a),d)},Hb:(a,b,c,d)=>{E.uniform3i(X(a),b,c,d)},Gb:(a,b,c)=>{if(96>=b){b*=3;for(var d=kc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);E.uniform3iv(X(a),d)},Db:(a,b,c,d,e)=>{E.uniform4f(X(a),b,c,d,e)},Cb:(a,b,c)=>{if(72>=b){var d=Y[4*b],e=w;c>>=2;b*=4;for(var f=
0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);E.uniform4fv(X(a),d)},Bb:(a,b,c,d,e)=>{E.uniform4i(X(a),b,c,d,e)},Ab:(a,b,c)=>{if(72>=b){b*=4;for(var d=kc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);E.uniform4iv(X(a),d)},zb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=Y[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=
w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);E.uniformMatrix2fv(X(a),!!c,e)},yb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=Y[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);E.uniformMatrix3fv(X(a),!!c,e)},xb:(a,b,c,d)=>{if(18>=b){var e=Y[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;
e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);E.uniformMatrix4fv(X(a),!!c,e)},wb:a=>{a=G[a];E.useProgram(a);E.Le=a},vb:a=>{E.validateProgram(G[a])},ub:(a,b)=>E.vertexAttrib1f(a,b),sb:(a,b)=>{E.vertexAttrib1f(a,w[b>>2])},rb:(a,b,c)=>E.vertexAttrib2f(a,b,c),qb:(a,b)=>{E.vertexAttrib2f(a,
w[b>>2],w[b+4>>2])},pb:(a,b,c,d)=>E.vertexAttrib3f(a,b,c,d),ob:(a,b)=>{E.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},nb:(a,b,c,d,e)=>E.vertexAttrib4f(a,b,c,d,e),mb:(a,b)=>{E.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},ga:(a,b)=>{E.vertexAttribDivisor(a,b)},lb:(a,b,c,d,e,f)=>{E.vertexAttribPointer(a,b,c,!!d,e,f)},kb:(a,b,c,d)=>E.viewport(a,b,c,d),f:()=>0,Aa:(a,b,c)=>lc(a,{se:u[c>>2],le:u[c+4>>2],Te:u[c+8>>2],Pe:b,fe:u[c+12>>2],Be:u[c+16>>2]}),F:(a,b)=>{a=U(a);return a?a.requestPointerLock?
Lb()?Zb(a):b?(Jb(Zb,2,[a]),1):-2:-1:-4},Sa:()=>{la("OOM")},l:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:mc(a,b),x:(a,b,c,d)=>nc(a,b,c,d,12,"blur"),c:Sb,g:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},y:(a,b,c,d)=>nc(a,b,c,d,13,"focus"),o:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;oc(a,b,c,d,"webkitfullscreenchange");return oc(a,b,c,d,"fullscreenchange")},Da:(a,b,c)=>qc()?-1:pc(a,b,c,26,"gamepadconnected"),Ca:(a,b,c)=>qc()?
-1:pc(a,b,c,27,"gamepaddisconnected"),r:(a,b,c,d)=>rc(a,b,c,d,2,"keydown"),p:(a,b,c,d)=>rc(a,b,c,d,1,"keypress"),q:(a,b,c,d)=>rc(a,b,c,d,3,"keyup"),Hd:(a,b,c,d)=>{Ab(()=>z(a)(b),c,d,b)},D:(a,b,c,d)=>tc(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>tc(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>tc(a,b,c,d,34,"mouseleave"),E:(a,b,c,d)=>tc(a,b,c,d,8,"mousemove"),C:(a,b,c,d)=>tc(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>document.body?.requestPointerLock?(a=U(a))?uc(a,b,c,d):-4:-1,n:(a,b,c,d)=>vc(a,b,c,d),k:(a,b,c)=>Ha(()=>z(a)(c),
b),t:(a,b,c,d)=>wc(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>wc(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>wc(a,b,c,d,24,"touchmove"),w:(a,b,c,d)=>wc(a,b,c,d,22,"touchstart"),m:(a,b,c)=>xc(a,b,c),z:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?yc(a,b,c,d):-1:-4,Ba:a=>document.title=a?A(r,a):"",e:()=>{la("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},Xa:(a,b)=>{var c=0,d=0,e;for(e of Bc()){var f=b+c;v[a+d>>2]=f;c+=O(e,f,Infinity)+1;d+=4}return 0},
Ya:(a,b)=>{var c=Bc();v[a>>2]=c.length;a=0;for(var d of c)a+=kb(d)+1;v[b>>2]=a;return 0},j:()=>52,G:()=>52,Wa:function(){return 70},db:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var t=a,F=r[g+m],L=Kc[t];0===F||10===F?((1===t?fa:k)(A(L)),L.length=0):L.push(F)}e+=l}v[d>>2]=e;return 0},La:Uc,Ja:Vc,Ka:Wc,Oa:Da,Za:(a,b)=>{Mc(r.subarray(a,a+b));return 0}};function Uc(a,b,c){var d=V();try{return z(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;Sc(1,0)}}
function Wc(a,b,c,d,e){var f=V();try{return z(a)(b,c,d,e)}catch(g){W(f);if(g!==g+0)throw g;Sc(1,0)}}function Vc(a,b,c,d){var e=V();try{return z(a)(b,c,d)}catch(f){W(e);if(f!==f+0)throw f;Sc(1,0)}}function Yc(a=[]){var b=Qc;a.unshift(ba);var c=a.length,d=Pb(4*(c+1)),e=d,f;for(f of a)v[e>>2]=Qb(f),e+=4;v[e>>2]=0;try{var g=b(c,d);ha=g;Da(g)}catch(l){Ca(l)}}
function Zc(a=aa){function b(){h.calledRun=!0;if(!p){$c.Jd();h.onRuntimeInitialized?.();h.noInitialRun||Yc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();sa.push(c)}ra(sa)}}if(0<y)va=Zc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();ra(ta);0<y?va=Zc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var $c;
(async function(){function a(c){c=$c=c.exports;Qc=h._main=c.Kd;P=c.Ld;Rc=c.Nd;Sc=c.Od;W=c.Pd;Pb=c.Qd;V=c.Rd;Tc=c.Id;ya=c.Md;c=Tc.buffer;q=new Int8Array(c);ia=new Int16Array(c);r=new Uint8Array(c);ja=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);ka=new BigInt64Array(c);new BigUint64Array(c);y--;h.monitorRunDependencies?.(y);0==y&&va&&(c=va,va=null,c());return $c}y++;h.monitorRunDependencies?.(y);var b={a:Xc};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ma??=h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";return a((await pa(b)).instance)})();Zc();
